server:
  port: 9604
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: Bhaumik@23
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 100000
      leak-detection-threshold: 10000
  application:
    name: spring-security-jdbc
    
